apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azurestartstop
  annotations:
    github.com/project-slug: devops-hemant/azurestartstop
spec:
  type: other
  owner: Hemant Sharma
  lifecycle: unknown
