name: Deploy dev

on:
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Building application..."

      - name: Test
        run: |
          echo "Running tests..."

      - name: Deploy
        run: |
          echo "Deploying application..."
